// Code generated by tygo. DO NOT EDIT.
// Code generated by tygo from internal/apitypes. DO NOT EDIT.
// Run `make types-gen` to regenerate.

import type { OrgNodeFields } from './types'

//////////
// source: types.go
/*
Package apitypes defines the data types that cross package boundaries
in the Grove backend. These are pure data — no methods, no logic —
and form the lingua franca between org, snapshot, pod, autosave,
and httpapi packages.
*/

export interface OrgNode extends OrgNodeFields {
  id: string;
  managerId: string;
  /**
   * SortIndex is omitempty so 0-valued (the common default) entries
   * don't bloat every JSON payload. Frontend code (`sortIndex ?? 0`)
   * treats undefined and 0 identically.
   */
  sortIndex?: number /* int */;
}
/**
 * OrgNodeUpdate carries optional field updates for a person.
 * Pointer fields: nil = not sent, zero value = set to empty/zero/false.
 */
export interface OrgNodeUpdate {
  type?: string;
  name?: string;
  role?: string;
  discipline?: string;
  team?: string;
  managerId?: string;
  status?: string;
  employmentType?: string;
  additionalTeams?: string;
  newRole?: string;
  newTeam?: string;
  level?: number /* int */;
  pod?: string;
  publicNote?: string;
  privateNote?: string;
  private?: boolean;
}
export interface Pod {
  id: string;
  name: string;
  team: string;
  managerId: string;
  publicNote?: string;
  privateNote?: string;
}
/**
 * PodUpdate carries optional field updates for a pod.
 */
export interface PodUpdate {
  name?: string;
  publicNote?: string;
  privateNote?: string;
}
export interface PodInfo extends Pod {
  memberCount: number /* int */;
}
export interface Settings {
  disciplineOrder: string[];
}
export interface MappedColumn {
  column: string;
  confidence: string; // "high", "medium", "none"
}
export interface PendingUpload {
  File: string /* []byte */;
  Filename: string;
  IsZip: boolean;
}
